name: IBM Cloud Auto Restart
  
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2

    - name: Install CF CLI
      run: |
         curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v6" | tar -zx
         sudo mv cf /usr/local/bin
         for i in {1..3};do
         cf l -a https://api.${{ "secrets.RGN$i" }}.cf.cloud.ibm.com login -u ${{ "secrets.MAIL$i" }} -p ${{ "secrets.PWD$i" }}
         cf rs ${{ secrets.CFNAME$1 }}
         sleep 600
