name: IBM Cloud Auto Restart
  
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '3 16 * * 6'
  watch:
    types: started

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2

    - name: Install CF CLI
      run: |
        for i in {1..3};do
        echo this is $i time;
        sleep 3
        done

     
